import streamlit as st
import datetime
import requests
import sys

BASE_URL = "http://localhost:8000" # FastAPI backend URL

st.set_page_config(
    page_title="Trip Planner Agent",
    page_icon="✈️",
    layout="centered",
    initial_sidebar_state="expanded",
)

st.title("✈️ Trip Planner Agentic Application")

# Initialize chat history
if "messages" not in st.session_state:
    st.session_state.messages = []


st.header("How can I help you in planning your trip? Let me know where do you want to go!")


# Chat input box
with st.form(key="query_form", clear_on_submit=True):
    user_input = st.text_input("User Input", placeholder="e.g. Plan a trip to Goa for 5 days")
    submit_button = st.form_submit_button(label="Send")



if submit_button and user_input.strip():
    try:
        with st.spinner("Agent is thinking..."):
            payload = {"question": user_input}
            response = requests.post(f"{BASE_URL}/query", params=payload)
            response.raise_for_status()        

        if response.status_code == 200:
            answer = response.json().get("answer", "No answer found.")
            markdown_content = f"""# 🌍 AI Travel Plan

            # **Generated:** {datetime.datetime.now().strftime('%Y-%m-%d at %H:%M')}  

            ---

            {answer}

            ---

            *This travel plan was generated by AI. Please verify all information, especially prices, operating hours, and travel requirements before your trip.*
            """
            st.markdown(markdown_content)
        else:
            st.error(f"Error: {response.status_code} - {response.text}")
    
    except requests.exceptions.RequestException as e:
        st.error(f"Request failed due to {e}")
